# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: monitoring-app
spec:
  selector:
    app: monitoring-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Exposes the service externally
